<?php

/**
 * csSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    olas
 * @subpackage model
 * @author     David Ward <dward@wevad.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class csSetting extends PlugincsSetting
{
}
