<?php

/**
 * School
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    olas
 * @subpackage model
 * @author     David Ward <dward@wevad.com>
 * @version    SVN: $Id$
 */
class School extends BaseSchool
{
	public function __toString() {
		return $this->getName;
	}

  public function getRUIncompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.ru_start IS NOT NULL')
      ->andWhere('s.ru_complete IS NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getRUIncompleteDate()
  {
    $studentAnswer = Doctrine::getTable('StudentAnswer')->createQuery('sa')
      ->innerJoin('sa.Student s')
      ->where('sa.assessment = ?', 'ru')
      ->andWhere('s.school_id = ?', $this->id)
      ->andWhere('s.ru_start IS NOT NULL')
      ->andWhere('s.ru_complete IS NULL')
      ->orderBy('sa.created_at DESC')
      ->limit(1)
      ->execute();

    /*
    $students = Doctrine_Query::create()
      ->from('Student s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.ru_start IS NOT NULL')
      ->andWhere('s.ru_complete IS NULL')
      ->orderBy('s.ru_complete DESC')
      ->limit(1)
      ->execute();
     */

    if (count($studentAnswer)) {
      if ($studentAnswer[0]->getCreatedAt()) {
        $dt = $studentAnswer[0]->getCreatedAt();
        $dt = date('m/d/Y', strtotime($dt));
      } else {
        $dt = '';
      }
    } else {
      $dt = '';
    }
    return $dt;
  }

  public function getRUCompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.ru_start IS NOT NULL')
      ->andWhere('s.ru_complete IS NOT NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getRUCompleteDate()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.ru_start IS NOT NULL')
      ->andWhere('s.ru_complete IS NOT NULL')
      ->orderBy('s.ru_complete DESC')
      ->limit(1)
      ->execute();

    if (count($students)) {
      $dt = $students[0]->getRUComplete();
      $dt = date('m/d/Y', strtotime($dt));
    } else {
      $dt = '';
    }
    return $dt;
  }




  public function getElemRUIncompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_ru_start IS NOT NULL')
      ->andWhere('s.elem_ru_complete IS NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getElemRUIncompleteDate()
  {
    $studentAnswer = Doctrine::getTable('StudentAnswer')->createQuery('sa')
      ->innerJoin('sa.Student s')
      ->where('sa.assessment = ?', 'elem_ru')
      ->andWhere('s.school_id = ?', $this->id)
      ->andWhere('s.elem_ru_start IS NOT NULL')
      ->andWhere('s.elem_ru_complete IS NULL')
      ->orderBy('sa.created_at DESC')
      ->limit(1)
      ->execute();

    /*
    $students = Doctrine_Query::create()
      ->from('Student s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_ru_start IS NOT NULL')
      ->andWhere('s.elem_ru_complete IS NULL')
      ->orderBy('s.elem_ru_complete DESC')
      ->limit(1)
      ->execute();
     */

    if (count($studentAnswer)) {
      if ($studentAnswer[0]->getCreatedAt()) {
        $dt = $studentAnswer[0]->getCreatedAt();
        $dt = date('m/d/Y', strtotime($dt));
      } else {
        $dt = '';
      }
    } else {
      $dt = '';
    }
    return $dt;
  }

  public function getElemRUCompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_ru_start IS NOT NULL')
      ->andWhere('s.elem_ru_complete IS NOT NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getElemRUCompleteDate()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_ru_start IS NOT NULL')
      ->andWhere('s.elem_ru_complete IS NOT NULL')
      ->orderBy('s.elem_ru_complete DESC')
      ->limit(1)
      ->execute();

    if (count($students)) {
      $dt = $students[0]->getElemRUComplete();
      $dt = date('m/d/Y', strtotime($dt));
    } else {
      $dt = '';
    }
    return $dt;
  }




  public function getMOIncompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.mo_start IS NOT NULL')
      ->andWhere('s.mo_complete IS NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getMOIncompleteDate()
  {
    $studentAnswer = Doctrine::getTable('StudentAnswer')->createQuery('sa')
      ->innerJoin('sa.Student s')
      ->where('sa.assessment = ?', 'mo')
      ->andWhere('s.school_id = ?', $this->id)
      ->andWhere('s.mo_start IS NOT NULL')
      ->andWhere('s.mo_complete IS NULL')
      ->orderBy('sa.created_at DESC')
      ->limit(1)
      ->execute();

    /*
    $students = Doctrine_Query::create()
      ->from('Student s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.mo_start IS NOT NULL')
      ->andWhere('s.mo_complete IS NULL')
      ->orderBy('s.mo_complete DESC')
      ->limit(1)
      ->execute();
     */

    if (count($studentAnswer)) {
      if ($studentAnswer[0]->getCreatedAt()) {
        $dt = $studentAnswer[0]->getCreatedAt();
        $dt = date('m/d/Y', strtotime($dt));
      } else {
        $dt = '';
      }
    } else {
      $dt = '';
    }
    return $dt;
  }

  public function getMOCompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.mo_start IS NOT NULL')
      ->andWhere('s.mo_complete IS NOT NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getMOCompleteDate()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.mo_start IS NOT NULL')
      ->andWhere('s.mo_complete IS NOT NULL')
      ->orderBy('s.mo_complete DESC')
      ->limit(1)
      ->execute();

    if (count($students)) {
      $dt = $students[0]->getMOComplete();
      $dt = date('m/d/Y', strtotime($dt));
    } else {
      $dt = '';
    }
    return $dt;
  }




  public function getElemMOIncompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_mo_start IS NOT NULL')
      ->andWhere('s.elem_mo_complete IS NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getElemMOIncompleteDate()
  {
    $studentAnswer = Doctrine::getTable('StudentAnswer')->createQuery('sa')
      ->innerJoin('sa.Student s')
      ->where('sa.assessment = ?', 'elem_mo')
      ->andWhere('s.school_id = ?', $this->id)
      ->andWhere('s.elem_mo_start IS NOT NULL')
      ->andWhere('s.elem_mo_complete IS NULL')
      ->orderBy('sa.created_at DESC')
      ->limit(1)
      ->execute();

    /*
    $students = Doctrine_Query::create()
      ->from('Student s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_mo_start IS NOT NULL')
      ->andWhere('s.elem_mo_complete IS NULL')
      ->orderBy('s.elem_mo_complete DESC')
      ->limit(1)
      ->execute();
     */

    if (count($studentAnswer)) {
      if ($studentAnswer[0]->getCreatedAt()) {
        $dt = $studentAnswer[0]->getCreatedAt();
        $dt = date('m/d/Y', strtotime($dt));
      } else {
        $dt = '';
      }
    } else {
      $dt = '';
    }
    return $dt;
  }

  public function getElemMOCompleteCount()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->select('COUNT(s.id) AS student_cnt')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_mo_start IS NOT NULL')
      ->andWhere('s.elem_mo_complete IS NOT NULL')
      ->execute();
    return $students[0]['student_cnt'];
  }

  public function getElemMOCompleteDate()
  {
    $students = Doctrine::getTable('Student')->createQuery('s')
      ->where('s.school_id = ?', $this->id)
      ->andWhere('s.elem_mo_start IS NOT NULL')
      ->andWhere('s.elem_mo_complete IS NOT NULL')
      ->orderBy('s.elem_mo_complete DESC')
      ->limit(1)
      ->execute();

    if (count($students)) {
      $dt = $students[0]->getElemMOComplete();
      $dt = date('m/d/Y', strtotime($dt));
    } else {
      $dt = '';
    }
    return $dt;
  }
}
