<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addquestionpage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('question_page', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'ru',
              1 => 'mo',
              ),
              'length' => NULL,
             ),
             'page' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'intro' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => 65532,
             ),
             'instructions' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => 65532,
             ),
             'scale_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 5,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'page' => 
              array(
              'fields' => 
              array(
               0 => 'page',
               1 => 'type',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('question_page');
    }
}