<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addstudentanswer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('student_answer', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'student_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 5,
             ),
             'question_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 5,
             ),
             'value' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'assessment' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'ru',
              1 => 'mo',
              ),
              'length' => NULL,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('student_answer');
    }
}