<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsession extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('session', array(
             'id' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 64,
             ),
             'sess_data' => 
             array(
              'type' => 'object',
              'length' => NULL,
             ),
             'sess_time' => 
             array(
              'type' => 'int',
              'length' => 11,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'sess_time' => 
              array(
              'fields' => 'sess_time',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('session');
    }
}