<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addscalevalue extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('scale_value', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'scale_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 5,
             ),
             'value' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 1,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('scale_value');
    }
}