<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addscale extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('scale', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'desc' => 
              array(
              'fields' => 'description',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('scale');
    }
}