<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addstudent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('student', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'school_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 5,
             ),
             'student_id' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 10,
             ),
             'ru_class_id' => 
             array(
              'type' => 'string',
              'length' => 2,
             ),
             'ethnicity' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'gender' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'mo_class_id' => 
             array(
              'type' => 'string',
              'length' => 2,
             ),
             'lesson_count' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'ru_start' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'ru_complete' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'mo_start' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'mo_complete' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'student' => 
              array(
              'fields' => 
              array(
               0 => 'school_id',
               1 => 'student_id',
               2 => 'mo_class_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('student');
    }
}