<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addquestion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('question', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 5,
             ),
             'question' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'ru_page_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'length' => 5,
             ),
             'ru_question_number' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'mo_page_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'length' => 5,
             ),
             'mo_question_number' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'ru_num' => 
              array(
              'fields' => 'ru_question_number',
              ),
              'mo_num' => 
              array(
              'fields' => 'mo_question_number',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('question');
    }
}