<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('student_answer', 'created_at', 'timestamp', '25', array(
             'notnull' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('student_answer', 'created_at');
    }
}
