<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('question', 'question_elem_ru_page_id_question_page_id', array(
             'name' => 'question_elem_ru_page_id_question_page_id',
             'local' => 'elem_ru_page_id',
             'foreign' => 'id',
             'foreignTable' => 'question_page',
             ));
        $this->addIndex('question', 'question_elem_ru_page_id', array(
             'fields' => 
             array(
              0 => 'elem_ru_page_id',
             ),
             ));
        $this->addIndex('question', 'sh_ru_num', array(
            'fields' => array(0=>'elem_ru_question_number'),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('question', 'question_elem_ru_page_id_question_page_id');
        $this->removeIndex('question', 'question_elem_ru_page_id', array(
             'fields' => 
             array(
              0 => 'elem_ru_page_id',
             ),
             ));
        $this->removeIndex('question', 'sh_ru_num', array(
             'fields' => 'elem_ru_question_number',
             ));
    }
}
