<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('question', 'elem_ru_page_id', 'integer', '5', array(
             'unsigned' => '1',
             ));
        $this->addColumn('question', 'elem_ru_question_number', 'integer', '8', array(
             ));
        /* These are actually varchar columns, no enum required
        $this->changeColumn('question_page', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'ru',
              1 => 'mo',
              2 => 'sh_ru',
             ),
             ));
        $this->changeColumn('student_answer', 'assessment', 'enum', '', array(
             'values' => 
             array(
              0 => 'ru',
              1 => 'mo',
              2 => 'sh_ru',
             ),
             'notnull' => '1',
             ));
         */
    }

    public function down()
    {
        $this->removeColumn('question', 'elem_ru_page_id');
        $this->removeColumn('question', 'elem_ru_question_number');
    }
}
