<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcssetting extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cs_setting', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'unique' => true,
              'notnull' => true,
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'default' => 'input',
              'length' => 255,
             ),
             'widget_options' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'value' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'setting_group' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 255,
             ),
             'setting_default' => 
             array(
              'type' => 'clob',
              'default' => '',
              'length' => NULL,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'cs_setting_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cs_setting');
    }
}