<?php

/**
 * sfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    olas
 * @subpackage model
 * @author     David Ward <dward@wevad.com>
 * @version    SVN: $Id$
 */
class sfGuardUserGroup extends PluginsfGuardUserGroup
{
}
