generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      actions:
        _new: { label: "Add a New User" }

      fields:
        password_again: { label: "Password (again)" }
        created_at: { label: "Created" }
        updated_at: { label: "Updated" }
        last_login: { label: "Last Login" }

      list:
        title:   User List
        display: [=username, created_at, updated_at, last_login]

      filter:
        display: [first_name, last_name, username, is_active, is_super_admin]

      form:
        class: sfGuardUserAdminForm
        display:
          "User":                   [first_name, last_name, email_address, username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
